# Generated by Django 3.0.6 on 2020-07-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolServices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
