# Generated by Django 3.0.6 on 2020-07-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolServices', '0002_auto_20200703_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='starting_price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
