# Generated by Django 3.0.6 on 2020-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolServices', '0005_auto_20200703_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(height_field=400, upload_to='poolServices/images/', width_field=400),
        ),
    ]
