# Generated by Django 3.0.6 on 2020-07-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolServices', '0007_auto_20200703_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='poolServices/images/'),
        ),
    ]
