# Generated by Django 3.0.6 on 2020-07-04 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolServices', '0008_auto_20200703_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='poolServices/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolServices.Service')),
            ],
        ),
    ]
