# Generated by Django 3.0.6 on 2020-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolServices', '0009_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='starting_price',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
